[general]
unauth_level = "none"

[[auth.simple]]
user = "marche"
passwd = "$2b$10$kftnDIDSFp51Zs7qILsbLuCs8ASTztz24iuW0lcMcBEuigwuGUfuW"  # "marche"

[interface.rpc]

[interface.udp]

[interface.web]
