#!/bin/sh
### BEGIN INIT INFO
# Provides:          marched
# Required-Start:    $local_fs $network
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: marched init script
### END INIT INFO

# Author: Alexander Lenz <alexander.lenz@frm2.tum.de>

if test -r /lib/lsb/init-functions ; then
                . /lib/lsb/init-functions
fi


BINARY_SHORT=marched
BINARY_FULL=$(which $BINARY_SHORT)
PIDFILE=/var/run/marched.pid
if [ ! -x "${BINARY_FULL}" ] ;
then
	log_progress_msg "Cannot find ${BINARY_SHORT}; Abort!\n"
	exit 127
fi

do_start()
{
	log_progress_msg "Start marched ..."
	start-stop-daemon --start --pidfile $PIDFILE --exec $BINARY_FULL -- -d
	return $?
}

do_stop()
{
	start-stop-daemon --stop --pidfile $PIDFILE
	return $?
}

do_status()
{
	status_of_proc -p $PIDFILE $BINARY_FULL $BINARY_SHORT
	return $?
}



case "$1" in
  start|"")
        do_start
        exit $?
        ;;
  restart|reload|force-reload)
	do_stop
	do_start
        exit $?
        ;;
  stop)
	do_stop
        exit $?
        ;;
  status)
        do_status
        exit $?
        ;;
  *)
        echo "Usage: ${0} [start|stop|status]" >&2
        exit 3
        ;;
esac

